# Generated by Django 4.2.7 on 2025-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
