# Generated by Django 4.2.7 on 2025-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_is_rejected_payment_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sender_name",
            field=models.CharField(
                blank=True,
                help_text="Name of person who made the payment",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="wakala_number",
            field=models.CharField(
                blank=True,
                help_text="Control/Wakala number from payment receipt",
                max_length=50,
                null=True,
            ),
        ),
    ]
