# Generated by Django 4.2.7 on 2025-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="university",
            field=models.CharField(
                default="University of Dar es Salaam", editable=False, max_length=200
            ),
        ),
    ]
