# Generated by Django 4.2.7 on 2025-12-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_update_application_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="application",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
