# Generated by Django 4.2.7 on 2025-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_application_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="date_of_admission",
            field=models.IntegerField(
                default=2024, help_text="Year of admission (e.g., 2023)"
            ),
        ),
    ]
