# Generated by Django 5.2.3 on 2026-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Year of achievement', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='achievements/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HighlightSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='highlights/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Highlight Slide',
                'verbose_name_plural': 'Highlight Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasurer_whatsapp', models.CharField(default='+255763167686', help_text='Treasurer WhatsApp number', max_length=20)),
                ('treasurer_name', models.CharField(default='IET Treasurer', help_text='Treasurer name', max_length=100)),
                ('lipa_namba', models.CharField(default='06989001197', help_text='LIPA NAMBA number', max_length=20)),
                ('lipa_namba_name', models.CharField(default='IET UDSM', help_text='LIPA NAMBA account name', max_length=100)),
                ('whatsapp_group_link', models.URLField(default='https://chat.whatsapp.com/HWTg4c6JKcUJi69RCZHaX7', help_text='WhatsApp group link')),
                ('contact_phone', models.CharField(default='0614021404', help_text='Main contact phone', max_length=20)),
                ('contact_email', models.EmailField(default='udsmiet@gmail.com', help_text='Main contact email', max_length=254)),
                ('contact_whatsapp', models.CharField(default='+255763167686', help_text='Main contact WhatsApp', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('avatar_initials', models.CharField(help_text='2-3 letters for avatar', max_length=3)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
