# Generated by Django 4.2.7 on 2025-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general_secretary", "General Secretary"),
                    ("treasurer", "Treasurer"),
                    ("chairperson", "Chairperson"),
                    ("vice_chairperson", "Vice Chairperson"),
                    ("coordinator", "Coordinator"),
                    ("admin", "Administrator"),
                ],
                help_text="Role for staff members",
                max_length=50,
                null=True,
            ),
        ),
    ]
