# Generated by Django 5.2.3 on 2026-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_college',
            field=models.CharField(blank=True, choices=[('CoET', 'College of Engineering and Technology'), ('SoMG', 'School of Mines and Geosciences'), ('CoAF', 'College of Agriculture and Food Sciences'), ('CoICT', 'College of Information and Communication Technologies')], help_text='Assigned college for Coordinator role', max_length=10, null=True),
        ),
    ]
